<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsightX.Application\InsightX.Application.csproj" />
    <ProjectReference Include="..\InsightX.Domain\InsightX.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.28" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.28">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.77.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\Mohamed_Lotfy\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>



</Project>
